### PR TITLE
Wefax defaults

### PR DESCRIPTION
**Pull request by lanceberc**
The OPC North Pacific wefax wasn't quite exactly the same region as the b&w faxes.
The Pt Reyes SST faxes needed some tweaking.

### CODE REVIEW

**Comment by ptulp** [comment]
I am not the owner of the weatherfax plugin.
You should open the pull request against seandepagnier/weatherfax_pi

**Comment by lanceberc** [comment]
I'm still figuring out git - I should have cloned his repository instead of yours but I wanted your changes. There's probably a way to get this done.

**Comment by lanceberc** [comment]
Ok, I made the pull request against Sean's repository. Sorry for the bother.

**Comment by lanceberc** [comment]
Closing this request.

**Pull request closed without merging**
